### ISSUE TITLE
VMware feature clarification

### ISSUE THREAD

**Issue by polarathene** [matterv/matterv#1]
[Phoronix recently published an article](https://www.phoronix.com/news/MatterV-0.7-Released) about the release of MatterV 0.7, [users are expressing curiosity about the extent of what that the VMWare support means](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1527897-kvm-powered-matterv-0-7-can-run-unmodified-vmware-vms?p=1528021#post1528021) as it's a tad vague.

Features I'd like to know myself are:
- Will MatterV have the same 3D accel capability? I recall the performance on a host with an nvidia GPU benchmarks like [Unigine Heaven](https://benchmark.unigine.com/heaven) had notable overhead on KVM/QEMU vs VMWare.
- Session snapshot / suspend. I don't quite recall the details for this one, but UEFI VM guests on VMWare could save/restore the guest session as-is along with this 3D accel support active. On KVM/QEMU I recall this not being well supported, at the time I think it may have been with BIOS only guests but not UEFI, may have had something to do with XSAVE.

At the same time, I recall some issues that were specific to VMWare that KVM/QEMU did not have. I have reported a few myself on VMWare's github repo, but I am curious if those drawbacks would also carry over or if MatterV being KVM based may mean a difference here in behaviour?

Or does the feature work more like a parser that reads the VMware specific configuration and some integration with VMWare tools, but otherwise maps that config to KVM/QEMU equivalents? Thus the features of interest I cited may not be available, while some of the bad issues may carry over (_related to VMWare tools, although the bugs may have been on the VMWare software itself rather than the guest tools_).

**Comment by dev-matterv** [comment]
@polarathene Thanks for your interest in this project.
1. We do plan to support feature like: https://blogs.vmware.com/apps/2018/09/using-gpus-with-virtual-machines-on-vsphere-part-3-installing-the-nvidia-grid-technology.html, but right now, it's not supported yet.
2. If the issue is related to 3D accel, I can not comment on it, as it's not supported yet. Thanks for the reminder, we will take a look at it when supporting this feature.
3. The behavior can be different on MatterV, as we reimplemented VMware tool related features in KVM. If you still have a list of those issues, we'd like to take a look. Maybe they are fixed in MatterV already.
4. We reimplemented VMware tools related features in KVM from scratch, and we tried to keep the same behavior as VMware as possible to keep compatible with VMware. So there are two parts: one is the VMware tools inside guest vm, another part is our implementation in KVM. If the issue is related to VMware tools itself, then there is nothing we can do, as we don't have the VMware tools's source code. If the issue is related to the implementation in the hypervisor, then that's something we can fix.

**Comment by polarathene** [comment]
> 3\. The behavior can be different on MatterV, as we reimplemented VMware tool related features in KVM. If you still have a list of those issues, we'd like to take a look. Maybe they are fixed in MatterV already.

I lack time to verify if any of these are still reproducible (_I'm not presently using VMware_):
- https://github.com/vmware/open-vm-tools/issues/601 (_despite being closed, I do reference context where it's still potentially an issue_)
- https://github.com/vmware/open-vm-tools/issues/443 (_not my issue but related copy/paste problem that happens with some wayland guests_)
- https://github.com/vmware/open-vm-tools/issues/669 (_distro packaging issue for `open-vm-tools`, due to lack of upstream maintained init examples, distros vary in quality_)
- https://github.com/vmware/open-vm-tools/issues/686 (_apparently not due to VMWare_ 🤷‍♂)
- https://github.com/vmware/open-vm-tools/issues/591 (_I think this is more of a client feature, it's broken for VMWare and equivalent support at the time for KVM/QEMU was iffy/tricky IIRC, if MatterV can do this well that'd be great_)
- https://github.com/vmware/open-vm-tools/issues/590 (_see comment below, related issues_)
- https://github.com/vmware/open-vm-tools/issues/589 (_I recall VMWare defaults at the time triggering many unwanted file copies between host/guest, it depended on the host and guest IIRC, if I had an ISO on the host as my last ctrl + c copy it'd cause large delays each time making multiple copies into the guest_)

You can go over that repo for a better idea in general about problems, [there's some issues I commented in](https://github.com/vmware/open-vm-tools/issues?q=is%3Aissue%20commenter%3A%40me%20) besides the ones I reported above.

---

I suppose the VMware support in MatterV is really a question of what that really means expectation wise. Is it more like "import/convert to KVM/QEMU", rather than retaining any features / bugs specific to VMware.

> 4\. So there are two parts: one is the VMware tools inside guest vm, another part is our implementation in KVM

Ah ok, so in the sense of the tools running within the guest, that's the same as it would be for VMware guests, if we refer to that as the server component, then you've implemented a KVM compatible client component 👍

I am not sure how this differs from VMware also [migrating from proprietary to KVM](https://www.phoronix.com/news/VMware-Workstation-KVM), documenting how MatterV differs in that aspect may also be helpful.

---

> 1. We do plan to support feature like: https://blogs.vmware.com/apps/2018/09/using-gpus-with-virtual-machines-on-vsphere-part-3-installing-the-nvidia-grid-technology.html, but right now, it's not supported yet.

My interest was in the 3D accel feature VMware had. It would be similar to virgl / venus in KVM/QEMU (_[QEMU 9.2 finally landed support for venus](https://www.phoronix.com/news/QEMU-9.2-Released)_), except virgl with nvidia eglstreams backend (_I think that's what I tested with_) was very inefficient (100% GPU utilization if I recall right, but much worse performance_), [Virtio-GPU Venus](https://docs.mesa3d.org/drivers/venus.html) is meant to be a bit different, there's also [native context support for AMD GPUs](https://www.phoronix.com/news/AMDGPU-VirtIO-Native-Mesa-25.0) (_[uses the `virglrenderer`](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21658#note_2739633), same as venus I think_). If helpful, [there is some activity by community here](https://gist.github.com/peppergrayxyz/fdc9042760273d137dddd3e97034385f) in troubleshooting getting that working.

I believe VMware 3D accel may have been using [their mesa driver](https://docs.mesa3d.org/drivers/svga3d.html) in the guest? While the other part for the host was proprietary, they announced some time ago that it was moved to use Vulkan and was similar to [Zink](https://docs.mesa3d.org/drivers/zink.html) IIRC.

> 2\. If the issue is related to 3D accel, I can not comment on it, as it's not supported yet. Thanks for the reminder, we will take a look at it when supporting this feature.

If MatterV is unable to leverage VMware's 3D accel (_understandable_), that's fine! KVM/QEMU support has been improving lately (_as per info above_), which from what I've heard can be quite competitive (_non-linux guests aside_).

**Comment by dev-matterv** [comment]
Yes, you are right, MatterV implements the "client" side for vmware tools.  It will be very similar to what VMware is trying to migrate to KVM for their VMware workstation software.
For 3D acceleration, I really haven't have time to take a look at it yet. If 3D acceleration is working in QEMU/KVM, then we should be able to support. 
Again, thanks for your interest in this project.
